#!/usr/bin/env node
/**
 * Generates a dated monitoring report for one dog, from a profile file.
 *
 *   node scripts/report.mjs examples/dog-profile.example.json
 *   node scripts/report.mjs my-dog.json --out report.md
 *
 * The report is written to be printed and handed to a veterinarian: trends
 * first, red flags surfaced, and unanswered domains listed as gaps rather
 * than silently omitted.
 */

import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join, resolve } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const args = process.argv.slice(2);
const profilePath = args.find((a) => !a.startsWith("--"));
const outIndex = args.indexOf("--out");
const outPath = outIndex !== -1 ? args[outIndex + 1] : null;

if (!profilePath) {
  console.error("Usage: node scripts/report.mjs <profile.json> [--out report.md]");
  process.exit(1);
}

const [profile, monitoring] = await Promise.all([
  readFile(resolve(profilePath), "utf8").then(JSON.parse),
  readFile(join(root, "data", "monitoring.json"), "utf8").then(JSON.parse),
]);

const domains = monitoring.domains;
const reviews = [...(profile.reviews ?? [])].sort((a, b) => a.date.localeCompare(b.date));

if (!reviews.length) {
  console.error("This profile has no reviews yet. Add at least one entry under \"reviews\".");
  process.exit(1);
}

const latest = reviews.at(-1);
const previous = reviews.at(-2);

const fmt = (value) => (value === undefined || value === null || value === "" ? "not recorded" : String(value));

/**
 * Direction of travel between the last two reviews, when both are numeric.
 * Whether a rising number is good or bad depends on the instrument, so each
 * domain declares it. Activity minutes going up is progress, pain scores
 * going up is not.
 */
function trend(domainId) {
  const now = latest.domains?.[domainId]?.score;
  const before = previous?.domains?.[domainId]?.score;
  if (typeof now !== "number" || typeof before !== "number") return null;

  const delta = now - before;
  const signed = `${delta > 0 ? "+" : ""}${delta}`;
  if (delta === 0) return { delta, worse: false, label: "unchanged" };

  const direction = domains.find((d) => d.id === domainId)?.direction ?? "neutral";
  if (direction === "neutral") return { delta, worse: false, label: `${signed}, changed` };

  const worse = direction === "higher_is_worse" ? delta > 0 : delta < 0;
  return { delta, worse, label: `${signed}, ${worse ? "worse" : "better"}` };
}

const answered = domains.filter((d) => latest.domains?.[d.id]);
const missing = domains.filter((d) => !latest.domains?.[d.id]);
const missingCore = missing.filter((d) => d.priority === "core");

const flagged = answered.flatMap((domain) => {
  const entry = latest.domains[domain.id];
  return (entry.flags ?? []).map((flag) => ({ domain, flag }));
});

const moved = answered
  .map((domain) => ({ domain, trend: trend(domain.id) }))
  .filter((row) => row.trend && row.trend.delta !== 0);

const dog = profile.dog ?? {};
const lines = [];

lines.push(`# Longevity monitoring report for ${fmt(dog.name)}`);
lines.push("");
lines.push(
  `**Review date:** ${fmt(latest.date)}  `,
  `**Dog:** ${fmt(dog.name)}, ${fmt(dog.breed)}, ${fmt(dog.sex)}, born ${fmt(dog.birth_date)}${
    dog.age_years ? ` (${dog.age_years} years)` : ""
  }  `,
  `**Weight:** ${fmt(latest.weight_kg)} kg  `,
  `**Reviews on record:** ${reviews.length}${previous ? ` (previous: ${previous.date})` : ""}  `,
  `**Framework:** ${monitoring.framework.name} v${monitoring.framework.version}`,
);
lines.push("");
lines.push("> Generated by Evidence Hound. This is a structured summary of owner observations, not a diagnosis.");
lines.push("> Bring it to your veterinarian rather than acting on it alone.");
lines.push("");

lines.push("## Summary");
lines.push("");
lines.push(`- **${answered.length} of ${domains.length}** domains assessed at this review`);
lines.push(`- **${flagged.length}** red flag${flagged.length === 1 ? "" : "s"} recorded`);
lines.push(`- **${moved.length}** domain${moved.length === 1 ? "" : "s"} changed since the previous review`);
if (missingCore.length) {
  lines.push(`- **${missingCore.length}** core domain${missingCore.length === 1 ? "" : "s"} not assessed, see gaps below`);
}
lines.push("");

if (flagged.length) {
  lines.push("## Red flags to raise first");
  lines.push("");
  lines.push("These are the items the framework marks as warranting attention. Listed first because appointment time is short.");
  lines.push("");
  for (const { domain, flag } of flagged) {
    lines.push(`- **${domain.name}.** ${flag}`);
  }
  lines.push("");
}

if (moved.length) {
  lines.push("## What changed since " + previous.date);
  lines.push("");
  lines.push("| Domain | Previous | Current | Change |");
  lines.push("| --- | --- | --- | --- |");
  for (const { domain, trend: t } of moved) {
    lines.push(
      `| ${domain.name} | ${fmt(previous.domains?.[domain.id]?.score)} | ${fmt(
        latest.domains[domain.id].score,
      )} | ${t.label} |`,
    );
  }
  lines.push("");
  lines.push("A domain moving two or more levels between reviews matters more than one that has been mildly abnormal for years.");
  lines.push("");
}

lines.push("## Full domain detail");
lines.push("");
for (const domain of domains) {
  const entry = latest.domains?.[domain.id];
  lines.push(`### ${domain.name}`);
  lines.push("");
  if (!entry) {
    lines.push(`_Not assessed at this review._ ${domain.priority === "core" ? "**This is a core domain.**" : ""}`);
    lines.push("");
    lines.push(`How to measure it: ${domain.measure}`);
    lines.push("");
    continue;
  }
  lines.push(`- **Score / value:** ${fmt(entry.score ?? entry.value)}`);
  if (entry.measured) lines.push(`- **Measured:** ${fmt(entry.measured)}`);
  if (entry.instrument) lines.push(`- **Instrument:** ${fmt(entry.instrument)}`);
  const t = trend(domain.id);
  if (t) lines.push(`- **Since last review:** ${t.label}`);
  if (entry.notes) lines.push(`- **Notes:** ${entry.notes}`);
  if (entry.flags?.length) lines.push(`- **Flags:** ${entry.flags.join("; ")}`);
  lines.push("");
}

if (missing.length) {
  lines.push("## Gaps in this review");
  lines.push("");
  lines.push("Domains with no entry. Listed explicitly so an unmeasured domain is never mistaken for a normal one.");
  lines.push("");
  for (const domain of missing) {
    lines.push(`- **${domain.name}**${domain.priority === "core" ? " *(core)*" : ""}. ${domain.cadence}`);
  }
  lines.push("");
}

const meds = profile.medications ?? [];
lines.push("## Current medications and supplements");
lines.push("");
if (meds.length) {
  lines.push("| Item | Dose | Started | Reason |");
  lines.push("| --- | --- | --- | --- |");
  for (const med of meds) {
    lines.push(`| ${fmt(med.name)} | ${fmt(med.dose)} | ${fmt(med.started)} | ${fmt(med.reason)} |`);
  }
  lines.push("");
  lines.push(
    "Ask at every review: is each of these still doing something measurable? Interaction risks worth naming out loud include two NSAIDs together, an NSAID with a corticosteroid, and selegiline with a serotonergic drug.",
  );
} else {
  lines.push("_None recorded._");
}
lines.push("");

lines.push("## Questions for this appointment");
lines.push("");
const questions = [
  ...flagged.map(({ domain, flag }) => `On ${domain.name.toLowerCase()}: ${flag}. What should we do about this?`),
  ...moved
    .filter((row) => row.trend.worse)
    .map(({ domain }) => `${domain.name} has moved in the wrong direction since ${previous.date}. Is that expected?`),
  ...missingCore.map((domain) => `We have not assessed ${domain.name.toLowerCase()}. Should we, today?`),
  ...(profile.questions ?? []),
];
if (questions.length) {
  for (const question of questions) lines.push(`- ${question}`);
} else {
  lines.push("- Nothing flagged this review. What should we watch for before the next one?");
}
lines.push("");
lines.push(`**Next review due:** ${fmt(profile.next_review ?? monitoring.framework.cadence_default)}`);
lines.push("");
lines.push("---");
lines.push("");
lines.push(
  "Evidence Hound · https://github.com/lextechx/evidence-hound · Content CC BY-SA 4.0 · Not veterinary advice.",
);

const report = lines.join("\n");

if (outPath) {
  await writeFile(resolve(outPath), report, "utf8");
  console.log(`✓ Report written to ${outPath}`);
} else {
  console.log(report);
}
